# Descripción

En este archivo se hará un análisis exploratorio el dataset maestro que contiene los datos históricos de los 12 meses de operaciones del último año de la empresa cyclistic.

El objetivo de este EDA es diagnostico ya que la intención es visualizar el estado actual del dataset, poder tomar desiciones al respecto y asegurar los siguientes aspectos:

- Relevantes → sirven para responder la pregunta

- Íntegros → no faltan partes críticas

- Consistentes → no se contradicen

- Correctos → tienen sentido lógico

- Confiables → puedes defenderlos ante otros

In [2]:
import pandas as pd

df=pd.read_csv('dataset_maestro_ciclistas.csv')
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member

In [3]:
df.shape

(5552994, 13)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5552994 entries, 0 to 5552993
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
dtypes: float64(4), object(9)
memory usage: 550.8+ MB

In [5]:
df.describe()

          start_lat     start_lng       end_lat       end_lng
count  5.552994e+06  5.552994e+06  5.547459e+06  5.547459e+06
mean   4.190366e+01 -8.764648e+01  4.190411e+01 -8.764683e+01
std    4.443323e-02  2.726130e-02  4.460469e-02  2.746640e-02
min    4.164850e+01 -8.789000e+01  4.149000e+01 -8.810000e+01
25%    4.188213e+01 -8.766000e+01  4.188241e+01 -8.766000e+01
50%    4.189859e+01 -8.764177e+01  4.189964e+01 -8.764275e+01
75%    4.193000e+01 -8.762991e+01  4.193000e+01 -8.763000e+01
max    4.207000e+01 -8.752000e+01  4.221000e+01 -8.742000e+01

In [6]:
df.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [7]:
df.isna().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1184673
start_station_id      1184673
end_station_name      1243305
end_station_id        1243305
start_lat                   0
start_lng                   0
end_lat                  5535
end_lng                  5535
member_casual               0
dtype: int64

In [8]:
df.isna().sum().sort_values(ascending=False)

end_station_name      1243305
end_station_id        1243305
start_station_id      1184673
start_station_name    1184673
end_lat                  5535
end_lng                  5535
started_at                  0
rideable_type               0
ride_id                     0
ended_at                    0
start_lat                   0
start_lng                   0
member_casual               0
dtype: int64

NOTA: Aun no se que columnas usare para mi analisis, pero al primer vistazo pense que quiza el nombre de la estacion seria util, pero resulta que hay muchos datos nulos. Supuestamente la latitud y longitud son un tipo de dato que indica ubicacion también, sera que me seran utiles esos datos?, sera que en caso de que los vaya a usar puedo cruzar la informacion de la latitud para rellenar los datos que faltan en el nombre de las estaciones?

Tambien tengo la duda sobre si deberia combinar la informacion de dos columnas para hacerla una sola. Lo analizaré después

In [9]:
df.nunique()

ride_id               5552994
rideable_type               2
started_at            5551938
ended_at              5550528
start_station_name       1893
start_station_id         3360
end_station_name         1901
end_station_id           3383
start_lat              118725
start_lng              116911
end_lat                  2030
end_lng                  2028
member_casual               2
dtype: int64

In [10]:
df.nunique().sort_values(ascending=True)

rideable_type               2
member_casual               2
start_station_name       1893
end_station_name         1901
end_lng                  2028
end_lat                  2030
start_station_id         3360
end_station_id           3383
start_lng              116911
start_lat              118725
ended_at              5550528
started_at            5551938
ride_id               5552994
dtype: int64

In [11]:
df['rideable_type'].value_counts()

rideable_type
electric_bike    3604953
classic_bike     1948041
Name: count, dtype: int64

In [12]:
df['member_casual'].value_counts()

member_casual
member    3553497
casual    1999497
Name: count, dtype: int64

Hasta este punto he hecho un EDA general de mi data set. He revisado forma, tipos de datos, valores nulos, unicos, y total de datos. Con esto hecho ahora voy a profundizar más sobre cada columna y asi poder determinar que acción tomar al respecto: eliminar, limpiar, dejarla o combinarlas. Con esto podre dejar las columnas que realmente me sirven.

Para esto empezare a analizar las columnas por orden de dependencia:

1. Nivel 1: Las "Columnas Identidad" (IDs)
Por qué primero: Porque si el ride_id está duplicado, no tiene sentido limpiar lo demás; primero debes resolver por qué hay basura repetida.

2. Nivel 2: Las "Columnas de Tiempo" (Fechas)
Por qué segundo: Porque las fechas son el corazón de este proyecto. Necesitas convertirlas a formato datetime antes de poder calcular nada más Estandarización de formato.

3. Nivel 3: Columnas Calculadas (Ingeniería de datos)
Por qué aquí: Una vez que las fechas están limpias, creas ride_length y day_of_week. Estas nuevas columnas te van a revelar Outliers (viajes de 0 segundos o de 1 mes) que antes no podías ver.

4. Nivel 4: Columnas Categóricas (Bicicletas y Usuarios)
Qué haces: Revisas rideable_type y member_casual.

5. Nivel 5: Columnas Geográficas y de Estación (Las más pesadas)
Por qué al final: Las columnas start_station_name, lat, lng, etc., suelen tener muchos nulos.

## Nivel 1: Columna de identidad [ride_id]

Este dato representa unicidad en este data set, debe ser único e irrepetible ya que cada uno indica el registro de cada viaje.

In [13]:
# Número de identificadores únicos de viaje

df['ride_id'].nunique()

5552994

In [14]:
# Longitud de los identificadores de viaje

df['ride_id'].astype('str').str.len().value_counts()

ride_id
16    5552994
Name: count, dtype: int64

In [15]:
# Tipos de datos en la columna 'ride_id'

df['ride_id'].apply(type).value_counts()

ride_id
<class 'str'>    5552994
Name: count, dtype: int64

In [16]:
# Tipos de datos en la columna 'ride_id'

df['ride_id'].dtype

dtype('O')

In [17]:
# Inspección visual de los primeros 15 valores en 'ride_id'

df['ride_id'].head(15)

0     7569BC890583FCD7
1     013609308856B7FC
2     EACACD3CE0607C0D
3     EAA2485BA64710D3
4     7F8BE2471C7F746B
5     0B8DD16A9B77A1C7
6     65DD88D2EA5AA24A
7     EAC4EE361C030130
8     46267A54446162B5
9     B5D4F9782121EA51
10    3C1E48C025E88653
11    B157E60BBF2BA5F6
12    81AE62C30F86C0D2
13    4978AFB4F96F17A6
14    1DCC4C0315A3B282
Name: ride_id, dtype: object

In [18]:
# Detección de posibles problemas en 'ride_id'

ide=df['ride_id'].astype('string')

extremos=ide != ide.str.strip() # espacios al inicio o final
medio=ide.str.contains(r"\S\s+\S", regex=True, na=False) # espacios en el medio
tabs=ide.str.contains(r"[\t\n\r]", regex=True, na=False) # tabulaciones o saltos de línea
caracteres_especiales=ide.str.contains(r"[^\w-]", regex=True, na=False) # caracteres no alfanuméricos ni guiones

extremos.sum(), medio.sum(), tabs.sum(), caracteres_especiales.sum()

(np.int64(0), np.int64(0), np.int64(0), np.int64(0))

## Nivel 1 completo

En el EDA del nivel 1 se encontro que la columna de ID esta limpia:

 - Sin nulos

 - Sin duplicados

 - Misma longitud

 - Sin espacios (bordes/medio)

 - Sin tabs / saltos invisibles

 - Sin caracteres especiales raros

## Nivel 2: Fechas 

Las fechas aportan un valor analítico muy importante porque revelan tendencias, estacionalidad y cohortes, sin embargo, suelen ser los datos más problemas en su formato.

Para este data set tenemos started_at y ended_at y haremos el EDA en dos momentos

- Data Profiling (Validación estructural de fechas): formato consistente, longitud, rango, nulos, duplicados esperables
- Business Rules Validation (Coherencia temporal): inicio ≤ fin, duración válida, detección de outliers

In [23]:
df[['started_at','ended_at']].head(10)

                started_at                 ended_at
0  2025-01-21 17:23:54.538  2025-01-21 17:37:52.015
1  2025-01-11 15:44:06.795  2025-01-11 15:49:11.139
2  2025-01-02 15:16:27.730  2025-01-02 15:28:03.230
3  2025-01-23 08:49:05.814  2025-01-23 08:52:40.047
4  2025-01-16 08:38:32.338  2025-01-16 08:41:06.767
5  2025-01-02 16:09:06.825  2025-01-02 16:10:55.784
6  2025-01-19 01:11:59.684  2025-01-19 01:15:54.187
7  2025-01-24 06:43:28.984  2025-01-24 07:01:38.943
8  2025-01-06 08:45:24.741  2025-01-06 08:50:20.458
9  2025-01-01 16:56:36.927  2025-01-01 17:03:26.608

In [ ]:
df['ended_at'].apply(type).value_counts()
df['started_at'].apply(type).value_counts()

started_at
<class 'str'>    5552994
Name: count, dtype: int64

In [ ]:
#Longitud de los valores en 'started_at' y 'ended_at'

df['started_at'].astype('str').str.len().value_counts()
df['ended_at'].astype('str').str.len().value_counts()

ended_at
23    5552994
Name: count, dtype: int64

In [ ]:
# Inspección visual de los separadores únicos en 'started_at' y 'ended_at' 

print(df['started_at'].replace(r'\d',' ', regex=True).unique())
print(df['ended_at'].replace(r'\d',' ', regex=True).unique())

['    -  -     :  :  .   ']
['    -  -     :  :  .   ']

In [46]:
d=df[['started_at','ended_at']].max()
a= df[['started_at','ended_at']].min()

d,a

(started_at    2025-12-31 23:53:24.274
 ended_at      2025-12-31 23:58:42.046
 dtype: object,
 started_at    2024-12-31 18:54:41.803
 ended_at      2025-01-01 00:00:01.447
 dtype: object)

In [52]:
partes_fecha=df['started_at'].str.split('-|:| ', expand=True)
partes_fecha.head()

      0   1   2   3   4       5
0  2025  01  21  17  23  54.538
1  2025  01  11  15  44  06.795
2  2025  01  02  15  16  27.730
3  2025  01  23  08  49  05.814
4  2025  01  16  08  38  32.338

In [ ]:
# Extracción de año, mes y día de 'started_at' para saber que valores únicos hay

partes_fecha_s=df['started_at'].str.split('-|:| ', expand=True)
año_s=partes_fecha_s[0].unique()
mes_s=partes_fecha_s[1].unique()
dia_s=partes_fecha_s[2].unique()

año_s, mes_s, dia_s.sort()

(array(['2025', '2024'], dtype=object),
 array(['01', '12', '02', '03', '04', '05', '06', '07', '08', '09', '10',
        '11'], dtype=object),
 array(['21', '11', '02', '23', '16', '19', '24', '06', '01', '31', '04',
        '10', '17', '09', '27', '13', '30', '15', '28', '18', '05', '12',
        '08', '29', '25', '03', '07', '22', '14', '26', '20'], dtype=object))

In [51]:
# Extracción de año, mes y día de 'ended_at' para saber que valores únicos hay

partes_fecha_e=df['ended_at'].str.split('-|:| ', expand=True)
año_e=partes_fecha_e[0].unique()
mes_e=partes_fecha_e[1].unique()
dia_e=sorted(partes_fecha_e[2].unique())

año_e, mes_e, dia_e

(array(['2025'], dtype=object),
 array(['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11',
        '12'], dtype=object),
 ['01',
  '02',
  '03',
  '04',
  '05',
  '06',
  '07',
  '08',
  '09',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '29',
  '30',
  '31'])

In [53]:
partes_hora_s=df['started_at'].str.split('-|:| ', expand=True)
hora=sorted(partes_hora_s[3].unique())
minuto=sorted(partes_hora_s[4].unique())
segundo=sorted(partes_hora_s[5].unique())
hora, minuto, segundo

(['00',
  '01',
  '02',
  '03',
  '04',
  '05',
  '06',
  '07',
  '08',
  '09',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23'],
 ['00',
  '01',
  '02',
  '03',
  '04',
  '05',
  '06',
  '07',
  '08',
  '09',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '29',
  '30',
  '31',
  '32',
  '33',
  '34',
  '35',
  '36',
  '37',
  '38',
  '39',
  '40',
  '41',
  '42',
  '43',
  '44',
  '45',
  '46',
  '47',
  '48',
  '49',
  '50',
  '51',
  '52',
  '53',
  '54',
  '55',
  '56',
  '57',
  '58',
  '59'],
 ['00.000',
  '00.001',
  '00.002',
  '00.003',
  '00.004',
  '00.005',
  '00.006',
  '00.007',
  '00.008',
  '00.009',
  '00.010',
  '00.011',
  '00.012',
  '00.013',
  '00.014',
  '00.015',
  '00.016',
  '00.017',
  '00.018',
  '00.019',
  '00.020',
  '00.021',
  '00.022',
  '00.023',
  '00.024',
  '00.025',
  '00.026',
  '00.027',
  '00.028',
  '00.029',
  '00.030',
  '00.031',
  '00.032',
  '00.033',
  '00.034',
  '00.035',
  '00.036',
  '00.037',
  '00.038',
  '00.039',
  '00.040',
  '00.041',
  '00.042',
  '00.043',
  '00.044',
  '00.045',
  '00.046',
  '00.047',
  '00.048',
  '00.049',
  '00.050',
  '00.051',
  '00.052',
  '00.053',
  '00.054',
  '00.055',
  '00.056',
  '00.057',
  '00.058',
  '00.059',
  '00.060',
  '00.061',
  '00.062',
  '00.063',
  '00.064',
  '00.065',
  '00.066',
  '00.067',
  '00.068',
  '00.069',
  '00.070',
  '00.071',
  '00.072',
  '00.073',
  '00.074',
  '00.075',
  '00.076',
  '00.077',
  '00.078',
  '00.079',
  '00.080',
  '00.081',
  '00.082',
  '00.083',
  '00.084',
  '00.085',
  '00.086',
  '00.087',
  '00.088',
  '00.089',
  '00.090',
  '00.091',
  '00.092',
  '00.093',
  '00.094',
  '00.095',
  '00.096',
  '00.097',
  '00.098',
  '00.099',
  '00.100',
  '00.101',
  '00.102',
  '00.103',
  '00.104',
  '00.105',
  '00.106',
  '00.107',
  '00.108',
  '00.109',
  '00.110',
  '00.111',
  '00.112',
  '00.113',
  '00.114',
  '00.115',
  '00.116',
  '00.117',
  '00.118',
  '00.119',
  '00.120',
  '00.121',
  '00.122',
  '00.123',
  '00.124',
  '00.125',
  '00.126',
  '00.127',
  '00.128',
  '00.129',
  '00.130',
  '00.131',
  '00.132',
  '00.133',
  '00.134',
  '00.135',
  '00.136',
  '00.137',
  '00.138',
  '00.139',
  '00.140',
  '00.141',
  '00.142',
  '00.143',
  '00.144',
  '00.145',
  '00.146',
  '00.147',
  '00.148',
  '00.149',
  '00.150',
  '00.151',
  '00.152',
  '00.153',
  '00.154',
  '00.155',
  '00.156',
  '00.157',
  '00.158',
  '00.159',
  '00.160',
  '00.161',
  '00.162',
  '00.163',
  '00.164',
  '00.165',
  '00.166',
  '00.167',
  '00.168',
  '00.169',
  '00.170',
  '00.171',
  '00.172',
  '00.173',
  '00.174',
  '00.175',
  '00.176',
  '00.177',
  '00.178',
  '00.179',
  '00.180',
  '00.181',
  '00.182',
  '00.183',
  '00.184',
  '00.185',
  '00.186',
  '00.187',
  '00.188',
  '00.189',
  '00.190',
  '00.191',
  '00.192',
  '00.193',
  '00.194',
  '00.195',
  '00.196',
  '00.197',
  '00.198',
  '00.199',
  '00.200',
  '00.201',
  '00.202',
  '00.203',
  '00.204',
  '00.205',
  '00.206',
  '00.207',
  '00.208',
  '00.209',
  '00.210',
  '00.211',
  '00.212',
  '00.213',
  '00.214',
  '00.215',
  '00.216',
  '00.217',
  '00.218',
  '00.219',
  '00.220',
  '00.221',
  '00.222',
  '00.223',
  '00.224',
  '00.225',
  '00.226',
  '00.227',
  '00.228',
  '00.229',
  '00.230',
  '00.231',
  '00.232',
  '00.233',
  '00.234',
  '00.235',
  '00.236',
  '00.237',
  '00.238',
  '00.239',
  '00.240',
  '00.241',
  '00.242',
  '00.243',
  '00.244',
  '00.245',
  '00.246',
  '00.247',
  '00.248',
  '00.249',
  '00.250',
  '00.251',
  '00.252',
  '00.253',
  '00.254',
  '00.255',
  '00.256',
  '00.257',
  '00.258',
  '00.259',
  '00.260',
  '00.261',
  '00.262',
  '00.263',
  '00.264',
  '00.265',
  '00.266',
  '00.267',
  '00.268',
  '00.269',
  '00.270',
  '00.271',
  '00.272',
  '00.273',
  '00.274',
  '00.275',
  '00.276',
  '00.277',
  '00.278',
  '00.279',
  '00.280',
  '00.281',
  '00.282',
  '00.283',
  '00.284',
  '00.285',
  '00.286',
  '00.287',
  '00.288',
  '00.289',
  '00.290',
  '00.291',
  '00.292',
  '00.293',
  '00.294',
  '00.295',
  '00.296',
  '00.297',
  '00.298',
  '00.299',
  '00.300',
  '00.301',
  '00.302',
  '00.303',
  '00.304',
  '00.305',
  '00.306',
  '00.307',
  '00.308',
  '00.309',
  '00.310',
  '00.311',
  '00.312',
  '00.313',
  '00.314',
  '00.315',
  '00.316',
  '00.317',
  '00.318',
  '00.319',
  '00.320',
  '00.321',
  '00.322',
  '00.323',
  '00.324',
  '00.325',
  '00.326',
  '00.327',
  '00.328',
  '00.329',
  '00.330',
  '00.331',
  '00.332',
  '00.333',
  '00.334',
  '00.335',
  '00.336',
  '00.337',
  '00.338',
  '00.339',
  '00.340',
  '00.341',
  '00.342',
  '00.343',
  '00.344',
  '00.345',
  '00.346',
  '00.347',
  '00.348',
  '00.349',
  '00.350',
  '00.351',
  '00.352',
  '00.353',
  '00.354',
  '00.355',
  '00.356',
  '00.357',
  '00.358',
  '00.359',
  '00.360',
  '00.361',
  '00.362',
  '00.363',
  '00.364',
  '00.365',
  '00.366',
  '00.367',
  '00.368',
  '00.369',
  '00.370',
  '00.371',
  '00.372',
  '00.373',
  '00.374',
  '00.375',
  '00.376',
  '00.377',
  '00.378',
  '00.379',
  '00.380',
  '00.381',
  '00.382',
  '00.383',
  '00.384',
  '00.385',
  '00.386',
  '00.387',
  '00.388',
  '00.389',
  '00.390',
  '00.391',
  '00.392',
  '00.393',
  '00.394',
  '00.395',
  '00.396',
  '00.397',
  '00.398',
  '00.399',
  '00.400',
  '00.401',
  '00.402',
  '00.403',
  '00.404',
  '00.405',
  '00.406',
  '00.407',
  '00.408',
  '00.409',
  '00.410',
  '00.411',
  '00.412',
  '00.413',
  '00.414',
  '00.415',
  '00.416',
  '00.417',
  '00.418',
  '00.419',
  '00.420',
  '00.421',
  '00.422',
  '00.423',
  '00.424',
  '00.425',
  '00.426',
  '00.427',
  '00.428',
  '00.429',
  '00.430',
  '00.431',
  '00.432',
  '00.433',
  '00.434',
  '00.435',
  '00.436',
  '00.437',
  '00.438',
  '00.439',
  '00.440',
  '00.441',
  '00.442',
  '00.443',
  '00.444',
  '00.445',
  '00.446',
  '00.447',
  '00.448',
  '00.449',
  '00.450',
  '00.451',
  '00.452',
  '00.453',
  '00.454',
  '00.455',
  '00.456',
  '00.457',
  '00.458',
  '00.459',
  '00.460',
  '00.461',
  '00.462',
  '00.463',
  '00.464',
  '00.465',
  '00.466',
  '00.467',
  '00.468',
  '00.469',
  '00.470',
  '00.471',
  '00.472',
  '00.473',
  '00.474',
  '00.475',
  '00.476',
  '00.477',
  '00.478',
  '00.479',
  '00.480',
  '00.481',
  '00.482',
  '00.483',
  '00.484',
  '00.485',
  '00.486',
  '00.487',
  '00.488',
  '00.489',
  '00.490',
  '00.491',
  '00.492',
  '00.493',
  '00.494',
  '00.495',
  '00.496',
  '00.497',
  '00.498',
  '00.499',
  '00.500',
  '00.501',
  '00.502',
  '00.503',
  '00.504',
  '00.505',
  '00.506',
  '00.507',
  '00.508',
  '00.509',
  '00.510',
  '00.511',
  '00.512',
  '00.513',
  '00.514',
  '00.515',
  '00.516',
  '00.517',
  '00.518',
  '00.519',
  '00.520',
  '00.521',
  '00.522',
  '00.523',
  '00.524',
  '00.525',
  '00.526',
  '00.527',
  '00.528',
  '00.529',
  '00.530',
  '00.531',
  '00.532',
  '00.533',
  '00.534',
  '00.535',
  '00.536',
  '00.537',
  '00.538',
  '00.539',
  '00.540',
  '00.541',
  '00.542',
  '00.543',
  '00.544',
  '00.545',
  '00.546',
  '00.547',
  '00.548',
  '00.549',
  '00.550',
  '00.551',
  '00.552',
  '00.553',
  '00.554',
  '00.555',
  '00.556',
  '00.557',
  '00.558',
  '00.559',
  '00.560',
  '00.561',
  '00.562',
  '00.563',
  '00.564',
  '00.565',
  '00.566',
  '00.567',
  '00.568',
  '00.569',
  '00.570',
  '00.571',
  '00.572',
  '00.573',
  '00.574',
  '00.575',
  '00.576',
  '00.577',
  '00.578',
  '00.579',
  '00.580',
  '00.581',
  '00.582',
  '00.583',
  '00.584',
  '00.585',
  '00.586',
  '00.587',
  '00.588',
  '00.589',
  '00.590',
  '00.591',
  '00.592',
  '00.593',
  '00.594',
  '00.595',
  '00.596',
  '00.597',
  '00.598',
  '00.599',
  '00.600',
  '00.601',
  '00.602',
  '00.603',
  '00.604',
  '00.605',
  '00.606',
  '00.607',
  '00.608',
  '00.609',
  '00.610',
  '00.611',
  '00.612',
  '00.613',
  '00.614',
  '00.615',
  '00.616',
  '00.617',
  '00.618',
  '00.619',
  '00.620',
  '00.621',
  '00.622',
  '00.623',
  '00.624',
  '00.625',
  '00.626',
  '00.627',
  '00.628',
  '00.629',
  '00.630',
  '00.631',
  '00.632',
  '00.633',
  '00.634',
  '00.635',
  '00.636',
  '00.637',
  '00.638',
  '00.639',
  '00.640',
  '00.641',
  '00.642',
  '00.643',
  '00.644',
  '00.645',
  '00.646',
  '00.647',
  '00.648',
  '00.649',
  '00.650',
  '00.651',
  '00.652',
  '00.653',
  '00.654',
  '00.655',
  '00.656',
  '00.657',
  '00.658',
  '00.659',
  '00.660',
  '00.661',
  '00.662',
  '00.663',
  '00.664',
  '00.665',
  '00.666',
  '00.667',
  '00.668',
  '00.669',
  '00.670',
  '00.671',
  '00.672',
  '00.673',
  '00.674',
  '00.675',
  '00.676',
  '00.677',
  '00.678',
  '00.679',
  '00.680',
  '00.681',
  '00.682',
  '00.683',
  '00.684',
  '00.685',
  '00.686',
  '00.687',
  '00.688',
  '00.689',
  '00.690',
  '00.691',
  '00.692',
  '00.693',
  '00.694',
  '00.695',
  '00.696',
  '00.697',
  '00.698',
  '00.699',
  '00.700',
  '00.701',
  '00.702',
  '00.703',
  '00.704',
  '00.705',
  '00.706',
  '00.707',
  '00.708',
  '00.709',
  '00.710',
  '00.711',
  '00.712',
  '00.713',
  '00.714',
  '00.715',
  '00.716',
  '00.717',
  '00.718',
  '00.719',
  '00.720',
  '00.721',
  '00.722',
  '00.723',
  '00.724',
  '00.725',
  '00.726',
  '00.727',
  '00.728',
  '00.729',
  '00.730',
  '00.731',
  '00.732',
  '00.733',
  '00.734',
  '00.735',
  '00.736',
  '00.737',
  '00.738',
  '00.739',
  '00.740',
  '00.741',
  '00.742',
  '00.743',
  '00.744',
  '00.745',
  '00.746',
  '00.747',
  '00.748',
  '00.749',
  '00.750',
  '00.751',
  '00.752',
  '00.753',
  '00.754',
  '00.755',
  '00.756',
  '00.757',
  '00.758',
  '00.759',
  '00.760',
  '00.761',
  '00.762',
  '00.763',
  '00.764',
  '00.765',
  '00.766',
  '00.767',
  '00.768',
  '00.769',
  '00.770',
  '00.771',
  '00.772',
  '00.773',
  '00.774',
  '00.775',
  '00.776',
  '00.777',
  '00.778',
  '00.779',
  '00.780',
  '00.781',
  '00.782',
  '00.783',
  '00.784',
  '00.785',
  '00.786',
  '00.787',
  '00.788',
  '00.789',
  '00.790',
  '00.791',
  '00.792',
  '00.793',
  '00.794',
  '00.795',
  '00.796',
  '00.797',
  '00.798',
  '00.799',
  '00.800',
  '00.801',
  '00.802',
  '00.803',
  '00.804',
  '00.805',
  '00.806',
  '00.807',
  '00.808',
  '00.809',
  '00.810',
  '00.811',
  '00.812',
  '00.813',
  '00.814',
  '00.815',
  '00.816',
  '00.817',
  '00.818',
  '00.819',
  '00.820',
  '00.821',
  '00.822',
  '00.823',
  '00.824',
  '00.825',
  '00.826',
  '00.827',
  '00.828',
  '00.829',
  '00.830',
  '00.831',
  '00.832',
  '00.833',
  '00.834',
  '00.835',
  '00.836',
  '00.837',
  '00.838',
  '00.839',
  '00.840',
  '00.841',
  '00.842',
  '00.843',
  '00.844',
  '00.845',
  '00.846',
  '00.847',
  '00.848',
  '00.849',
  '00.850',
  '00.851',
  '00.852',
  '00.853',
  '00.854',
  '00.855',
  '00.856',
  '00.857',
  '00.858',
  '00.859',
  '00.860',
  '00.861',
  '00.862',
  '00.863',
  '00.864',
  '00.865',
  '00.866',
  '00.867',
  '00.868',
  '00.869',
  '00.870',
  '00.871',
  '00.872',
  '00.873',
  '00.874',
  '00.875',
  '00.876',
  '00.877',
  '00.878',
  '00.879',
  '00.880',
  '00.881',
  '00.882',
  '00.883',
  '00.884',
  '00.885',
  '00.886',
  '00.887',
  '00.888',
  '00.889',
  '00.890',
  '00.891',
  '00.892',
  '00.893',
  '00.894',
  '00.895',
  '00.896',
  '00.897',
  '00.898',
  '00.899',
  '00.900',
  '00.901',
  '00.902',
  '00.903',
  '00.904',
  '00.905',
  '00.906',
  '00.907',
  '00.908',
  '00.909',
  '00.910',
  '00.911',
  '00.912',
  '00.913',
  '00.914',
  '00.915',
  '00.916',
  '00.917',
  '00.918',
  '00.919',
  '00.920',
  '00.921',
  '00.922',
  '00.923',
  '00.924',
  '00.925',
  '00.926',
  '00.927',
  '00.928',
  '00.929',
  '00.930',
  '00.931',
  '00.932',
  '00.933',
  '00.934',
  '00.935',
  '00.936',
  '00.937',
  '00.938',
  '00.939',
  '00.940',
  '00.941',
  '00.942',
  '00.943',
  '00.944',
  '00.945',
  '00.946',
  '00.947',
  '00.948',
  '00.949',
  '00.950',
  '00.951',
  '00.952',
  '00.953',
  '00.954',
  '00.955',
  '00.956',
  '00.957',
  '00.958',
  '00.959',
  '00.960',
  '00.961',
  '00.962',
  '00.963',
  '00.964',
  '00.965',
  '00.966',
  '00.967',
  '00.968',
  '00.969',
  '00.970',
  '00.971',
  '00.972',
  '00.973',
  '00.974',
  '00.975',
  '00.976',
  '00.977',
  '00.978',
  '00.979',
  '00.980',
  '00.981',
  '00.982',
  '00.983',
  '00.984',
  '00.985',
  '00.986',
  '00.987',
  '00.988',
  '00.989',
  '00.990',
  '00.991',
  '00.992',
  '00.993',
  '00.994',
  '00.995',
  '00.996',
  '00.997',
  '00.998',
  '00.999',
  ...])

In [61]:
partes_hora_e=df['ended_at'].str.split('-|:| ', expand=True)
hora=sorted(partes_hora_e[3].unique())
minuto=sorted(partes_hora_e[4].unique())
segundo=sorted(partes_hora_e[5].unique())
hora, minuto, segundo

(['00',
  '01',
  '02',
  '03',
  '04',
  '05',
  '06',
  '07',
  '08',
  '09',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23'],
 ['00',
  '01',
  '02',
  '03',
  '04',
  '05',
  '06',
  '07',
  '08',
  '09',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '29',
  '30',
  '31',
  '32',
  '33',
  '34',
  '35',
  '36',
  '37',
  '38',
  '39',
  '40',
  '41',
  '42',
  '43',
  '44',
  '45',
  '46',
  '47',
  '48',
  '49',
  '50',
  '51',
  '52',
  '53',
  '54',
  '55',
  '56',
  '57',
  '58',
  '59'],
 ['00.000',
  '00.001',
  '00.002',
  '00.003',
  '00.004',
  '00.005',
  '00.006',
  '00.007',
  '00.008',
  '00.009',
  '00.010',
  '00.011',
  '00.012',
  '00.013',
  '00.014',
  '00.015',
  '00.016',
  '00.017',
  '00.018',
  '00.019',
  '00.020',
  '00.021',
  '00.022',
  '00.023',
  '00.024',
  '00.025',
  '00.026',
  '00.027',
  '00.028',
  '00.029',
  '00.030',
  '00.031',
  '00.032',
  '00.033',
  '00.034',
  '00.035',
  '00.036',
  '00.037',
  '00.038',
  '00.039',
  '00.040',
  '00.041',
  '00.042',
  '00.043',
  '00.044',
  '00.045',
  '00.046',
  '00.047',
  '00.048',
  '00.049',
  '00.050',
  '00.051',
  '00.052',
  '00.053',
  '00.054',
  '00.055',
  '00.056',
  '00.057',
  '00.058',
  '00.059',
  '00.060',
  '00.061',
  '00.062',
  '00.063',
  '00.064',
  '00.065',
  '00.066',
  '00.067',
  '00.068',
  '00.069',
  '00.070',
  '00.071',
  '00.072',
  '00.073',
  '00.074',
  '00.075',
  '00.076',
  '00.077',
  '00.078',
  '00.079',
  '00.080',
  '00.081',
  '00.082',
  '00.083',
  '00.084',
  '00.085',
  '00.086',
  '00.087',
  '00.088',
  '00.089',
  '00.090',
  '00.091',
  '00.092',
  '00.093',
  '00.094',
  '00.095',
  '00.096',
  '00.097',
  '00.098',
  '00.099',
  '00.100',
  '00.101',
  '00.102',
  '00.103',
  '00.104',
  '00.105',
  '00.106',
  '00.107',
  '00.108',
  '00.109',
  '00.110',
  '00.111',
  '00.112',
  '00.113',
  '00.114',
  '00.115',
  '00.116',
  '00.117',
  '00.118',
  '00.119',
  '00.120',
  '00.121',
  '00.122',
  '00.123',
  '00.124',
  '00.125',
  '00.126',
  '00.127',
  '00.128',
  '00.129',
  '00.130',
  '00.131',
  '00.132',
  '00.133',
  '00.134',
  '00.135',
  '00.136',
  '00.137',
  '00.138',
  '00.139',
  '00.140',
  '00.141',
  '00.142',
  '00.143',
  '00.144',
  '00.145',
  '00.146',
  '00.147',
  '00.148',
  '00.149',
  '00.150',
  '00.151',
  '00.152',
  '00.153',
  '00.154',
  '00.155',
  '00.156',
  '00.157',
  '00.158',
  '00.159',
  '00.160',
  '00.161',
  '00.162',
  '00.163',
  '00.164',
  '00.165',
  '00.166',
  '00.167',
  '00.168',
  '00.169',
  '00.170',
  '00.171',
  '00.172',
  '00.173',
  '00.174',
  '00.175',
  '00.176',
  '00.177',
  '00.178',
  '00.179',
  '00.180',
  '00.181',
  '00.182',
  '00.183',
  '00.184',
  '00.185',
  '00.186',
  '00.187',
  '00.188',
  '00.189',
  '00.190',
  '00.191',
  '00.192',
  '00.193',
  '00.194',
  '00.195',
  '00.196',
  '00.197',
  '00.198',
  '00.199',
  '00.200',
  '00.201',
  '00.202',
  '00.203',
  '00.204',
  '00.205',
  '00.206',
  '00.207',
  '00.208',
  '00.209',
  '00.210',
  '00.211',
  '00.212',
  '00.213',
  '00.214',
  '00.215',
  '00.216',
  '00.217',
  '00.218',
  '00.219',
  '00.220',
  '00.221',
  '00.222',
  '00.223',
  '00.224',
  '00.225',
  '00.226',
  '00.227',
  '00.228',
  '00.229',
  '00.230',
  '00.231',
  '00.232',
  '00.233',
  '00.234',
  '00.235',
  '00.236',
  '00.237',
  '00.238',
  '00.239',
  '00.240',
  '00.241',
  '00.242',
  '00.243',
  '00.244',
  '00.245',
  '00.246',
  '00.247',
  '00.248',
  '00.249',
  '00.250',
  '00.251',
  '00.252',
  '00.253',
  '00.254',
  '00.255',
  '00.256',
  '00.257',
  '00.258',
  '00.259',
  '00.260',
  '00.261',
  '00.262',
  '00.263',
  '00.264',
  '00.265',
  '00.266',
  '00.267',
  '00.268',
  '00.269',
  '00.270',
  '00.271',
  '00.272',
  '00.273',
  '00.274',
  '00.275',
  '00.276',
  '00.277',
  '00.278',
  '00.279',
  '00.280',
  '00.281',
  '00.282',
  '00.283',
  '00.284',
  '00.285',
  '00.286',
  '00.287',
  '00.288',
  '00.289',
  '00.290',
  '00.291',
  '00.292',
  '00.293',
  '00.294',
  '00.295',
  '00.296',
  '00.297',
  '00.298',
  '00.299',
  '00.300',
  '00.301',
  '00.302',
  '00.303',
  '00.304',
  '00.305',
  '00.306',
  '00.307',
  '00.308',
  '00.309',
  '00.310',
  '00.311',
  '00.312',
  '00.313',
  '00.314',
  '00.315',
  '00.316',
  '00.317',
  '00.318',
  '00.319',
  '00.320',
  '00.321',
  '00.322',
  '00.323',
  '00.324',
  '00.325',
  '00.326',
  '00.327',
  '00.328',
  '00.329',
  '00.330',
  '00.331',
  '00.332',
  '00.333',
  '00.334',
  '00.335',
  '00.336',
  '00.337',
  '00.338',
  '00.339',
  '00.340',
  '00.341',
  '00.342',
  '00.343',
  '00.344',
  '00.345',
  '00.346',
  '00.347',
  '00.348',
  '00.349',
  '00.350',
  '00.351',
  '00.352',
  '00.353',
  '00.354',
  '00.355',
  '00.356',
  '00.357',
  '00.358',
  '00.359',
  '00.360',
  '00.361',
  '00.362',
  '00.363',
  '00.364',
  '00.365',
  '00.366',
  '00.367',
  '00.368',
  '00.369',
  '00.370',
  '00.371',
  '00.372',
  '00.373',
  '00.374',
  '00.375',
  '00.376',
  '00.377',
  '00.378',
  '00.379',
  '00.380',
  '00.381',
  '00.382',
  '00.383',
  '00.384',
  '00.385',
  '00.386',
  '00.387',
  '00.388',
  '00.389',
  '00.390',
  '00.391',
  '00.392',
  '00.393',
  '00.394',
  '00.395',
  '00.396',
  '00.397',
  '00.398',
  '00.399',
  '00.400',
  '00.401',
  '00.402',
  '00.403',
  '00.404',
  '00.405',
  '00.406',
  '00.407',
  '00.408',
  '00.409',
  '00.410',
  '00.411',
  '00.412',
  '00.413',
  '00.414',
  '00.415',
  '00.416',
  '00.417',
  '00.418',
  '00.419',
  '00.420',
  '00.421',
  '00.422',
  '00.423',
  '00.424',
  '00.425',
  '00.426',
  '00.427',
  '00.428',
  '00.429',
  '00.430',
  '00.431',
  '00.432',
  '00.433',
  '00.434',
  '00.435',
  '00.436',
  '00.437',
  '00.438',
  '00.439',
  '00.440',
  '00.441',
  '00.442',
  '00.443',
  '00.444',
  '00.445',
  '00.446',
  '00.447',
  '00.448',
  '00.449',
  '00.450',
  '00.451',
  '00.452',
  '00.453',
  '00.454',
  '00.455',
  '00.456',
  '00.457',
  '00.458',
  '00.459',
  '00.460',
  '00.461',
  '00.462',
  '00.463',
  '00.464',
  '00.465',
  '00.466',
  '00.467',
  '00.468',
  '00.469',
  '00.470',
  '00.471',
  '00.472',
  '00.473',
  '00.474',
  '00.475',
  '00.476',
  '00.477',
  '00.478',
  '00.479',
  '00.480',
  '00.481',
  '00.482',
  '00.483',
  '00.484',
  '00.485',
  '00.486',
  '00.487',
  '00.488',
  '00.489',
  '00.490',
  '00.491',
  '00.492',
  '00.493',
  '00.494',
  '00.495',
  '00.496',
  '00.497',
  '00.498',
  '00.499',
  '00.500',
  '00.501',
  '00.502',
  '00.503',
  '00.504',
  '00.505',
  '00.506',
  '00.507',
  '00.508',
  '00.509',
  '00.510',
  '00.511',
  '00.512',
  '00.513',
  '00.514',
  '00.515',
  '00.516',
  '00.517',
  '00.518',
  '00.519',
  '00.520',
  '00.521',
  '00.522',
  '00.523',
  '00.524',
  '00.525',
  '00.526',
  '00.527',
  '00.528',
  '00.529',
  '00.530',
  '00.531',
  '00.532',
  '00.533',
  '00.534',
  '00.535',
  '00.536',
  '00.537',
  '00.538',
  '00.539',
  '00.540',
  '00.541',
  '00.542',
  '00.543',
  '00.544',
  '00.545',
  '00.546',
  '00.547',
  '00.548',
  '00.549',
  '00.550',
  '00.551',
  '00.552',
  '00.553',
  '00.554',
  '00.555',
  '00.556',
  '00.557',
  '00.558',
  '00.559',
  '00.560',
  '00.561',
  '00.562',
  '00.563',
  '00.564',
  '00.565',
  '00.566',
  '00.567',
  '00.568',
  '00.569',
  '00.570',
  '00.571',
  '00.572',
  '00.573',
  '00.574',
  '00.575',
  '00.576',
  '00.577',
  '00.578',
  '00.579',
  '00.580',
  '00.581',
  '00.582',
  '00.583',
  '00.584',
  '00.585',
  '00.586',
  '00.587',
  '00.588',
  '00.589',
  '00.590',
  '00.591',
  '00.592',
  '00.593',
  '00.594',
  '00.595',
  '00.596',
  '00.597',
  '00.598',
  '00.599',
  '00.600',
  '00.601',
  '00.602',
  '00.603',
  '00.604',
  '00.605',
  '00.606',
  '00.607',
  '00.608',
  '00.609',
  '00.610',
  '00.611',
  '00.612',
  '00.613',
  '00.614',
  '00.615',
  '00.616',
  '00.617',
  '00.618',
  '00.619',
  '00.620',
  '00.621',
  '00.622',
  '00.623',
  '00.624',
  '00.625',
  '00.626',
  '00.627',
  '00.628',
  '00.629',
  '00.630',
  '00.631',
  '00.632',
  '00.633',
  '00.634',
  '00.635',
  '00.636',
  '00.637',
  '00.638',
  '00.639',
  '00.640',
  '00.641',
  '00.642',
  '00.643',
  '00.644',
  '00.645',
  '00.646',
  '00.647',
  '00.648',
  '00.649',
  '00.650',
  '00.651',
  '00.652',
  '00.653',
  '00.654',
  '00.655',
  '00.656',
  '00.657',
  '00.658',
  '00.659',
  '00.660',
  '00.661',
  '00.662',
  '00.663',
  '00.664',
  '00.665',
  '00.666',
  '00.667',
  '00.668',
  '00.669',
  '00.670',
  '00.671',
  '00.672',
  '00.673',
  '00.674',
  '00.675',
  '00.676',
  '00.677',
  '00.678',
  '00.679',
  '00.680',
  '00.681',
  '00.682',
  '00.683',
  '00.684',
  '00.685',
  '00.686',
  '00.687',
  '00.688',
  '00.689',
  '00.690',
  '00.691',
  '00.692',
  '00.693',
  '00.694',
  '00.695',
  '00.696',
  '00.697',
  '00.698',
  '00.699',
  '00.700',
  '00.701',
  '00.702',
  '00.703',
  '00.704',
  '00.705',
  '00.706',
  '00.707',
  '00.708',
  '00.709',
  '00.710',
  '00.711',
  '00.712',
  '00.713',
  '00.714',
  '00.715',
  '00.716',
  '00.717',
  '00.718',
  '00.719',
  '00.720',
  '00.721',
  '00.722',
  '00.723',
  '00.724',
  '00.725',
  '00.726',
  '00.727',
  '00.728',
  '00.729',
  '00.730',
  '00.731',
  '00.732',
  '00.733',
  '00.734',
  '00.735',
  '00.736',
  '00.737',
  '00.738',
  '00.739',
  '00.740',
  '00.741',
  '00.742',
  '00.743',
  '00.744',
  '00.745',
  '00.746',
  '00.747',
  '00.748',
  '00.749',
  '00.750',
  '00.751',
  '00.752',
  '00.753',
  '00.754',
  '00.755',
  '00.756',
  '00.757',
  '00.758',
  '00.759',
  '00.760',
  '00.761',
  '00.762',
  '00.763',
  '00.764',
  '00.765',
  '00.766',
  '00.767',
  '00.768',
  '00.769',
  '00.770',
  '00.771',
  '00.772',
  '00.773',
  '00.774',
  '00.775',
  '00.776',
  '00.777',
  '00.778',
  '00.779',
  '00.780',
  '00.781',
  '00.782',
  '00.783',
  '00.784',
  '00.785',
  '00.786',
  '00.787',
  '00.788',
  '00.789',
  '00.790',
  '00.791',
  '00.792',
  '00.793',
  '00.794',
  '00.795',
  '00.796',
  '00.797',
  '00.798',
  '00.799',
  '00.800',
  '00.801',
  '00.802',
  '00.803',
  '00.804',
  '00.805',
  '00.806',
  '00.807',
  '00.808',
  '00.809',
  '00.810',
  '00.811',
  '00.812',
  '00.813',
  '00.814',
  '00.815',
  '00.816',
  '00.817',
  '00.818',
  '00.819',
  '00.820',
  '00.821',
  '00.822',
  '00.823',
  '00.824',
  '00.825',
  '00.826',
  '00.827',
  '00.828',
  '00.829',
  '00.830',
  '00.831',
  '00.832',
  '00.833',
  '00.834',
  '00.835',
  '00.836',
  '00.837',
  '00.838',
  '00.839',
  '00.840',
  '00.841',
  '00.842',
  '00.843',
  '00.844',
  '00.845',
  '00.846',
  '00.847',
  '00.848',
  '00.849',
  '00.850',
  '00.851',
  '00.852',
  '00.853',
  '00.854',
  '00.855',
  '00.856',
  '00.857',
  '00.858',
  '00.859',
  '00.860',
  '00.861',
  '00.862',
  '00.863',
  '00.864',
  '00.865',
  '00.866',
  '00.867',
  '00.868',
  '00.869',
  '00.870',
  '00.871',
  '00.872',
  '00.873',
  '00.874',
  '00.875',
  '00.876',
  '00.877',
  '00.878',
  '00.879',
  '00.880',
  '00.881',
  '00.882',
  '00.883',
  '00.884',
  '00.885',
  '00.886',
  '00.887',
  '00.888',
  '00.889',
  '00.890',
  '00.891',
  '00.892',
  '00.893',
  '00.894',
  '00.895',
  '00.896',
  '00.897',
  '00.898',
  '00.899',
  '00.900',
  '00.901',
  '00.902',
  '00.903',
  '00.904',
  '00.905',
  '00.906',
  '00.907',
  '00.908',
  '00.909',
  '00.910',
  '00.911',
  '00.912',
  '00.913',
  '00.914',
  '00.915',
  '00.916',
  '00.917',
  '00.918',
  '00.919',
  '00.920',
  '00.921',
  '00.922',
  '00.923',
  '00.924',
  '00.925',
  '00.926',
  '00.927',
  '00.928',
  '00.929',
  '00.930',
  '00.931',
  '00.932',
  '00.933',
  '00.934',
  '00.935',
  '00.936',
  '00.937',
  '00.938',
  '00.939',
  '00.940',
  '00.941',
  '00.942',
  '00.943',
  '00.944',
  '00.945',
  '00.946',
  '00.947',
  '00.948',
  '00.949',
  '00.950',
  '00.951',
  '00.952',
  '00.953',
  '00.954',
  '00.955',
  '00.956',
  '00.957',
  '00.958',
  '00.959',
  '00.960',
  '00.961',
  '00.962',
  '00.963',
  '00.964',
  '00.965',
  '00.966',
  '00.967',
  '00.968',
  '00.969',
  '00.970',
  '00.971',
  '00.972',
  '00.973',
  '00.974',
  '00.975',
  '00.976',
  '00.977',
  '00.978',
  '00.979',
  '00.980',
  '00.981',
  '00.982',
  '00.983',
  '00.984',
  '00.985',
  '00.986',
  '00.987',
  '00.988',
  '00.989',
  '00.990',
  '00.991',
  '00.992',
  '00.993',
  '00.994',
  '00.995',
  '00.996',
  '00.997',
  '00.998',
  '00.999',
  ...])

In [54]:
df['started_at'].isna().sum()
df['ended_at'].isna().sum()

np.int64(0)

In [ ]:
#Revisamos duplicados, aunque es logico que existan duplicados en fechas de inicio y fin de viajes, pero sin que la cifra sea exagerada
#Además estos duplicados se conservan ya que los identificadores de viaje son únicos, entonces no afectan la unicidad del registro.

duplicados_s=df['started_at'].duplicated().sum()
duplicados_e=df['ended_at'].duplicated().sum()

duplicados_s, duplicados_e

(np.int64(1056), np.int64(2466))

### Data profiling completo

Se verificó que no hay nulos, las fechas tienen longitud y formato coherente para todos los registros de started_at y ended_at, hay duplicados válidos. Aún no se procede hacer el cambio de tipo de dato: str--> datetime